### ISSUE TITLE
Styling update

### ISSUE THREAD

**Issue by duffn** [citizenparker/swsheets#111]
Any interest in a minor styling update? Nothing too involved, but maybe just a Bootswatch style for a little refresh? I played around a bit with Flatly last night: https://github.com/swsheets/swsheets/compare/master...duffn:duffn/flatly-restyle?expand=1

<img width="1506" alt="Screen Shot 2019-12-13 at 6 47 08 AM" src="https://user-images.githubusercontent.com/3457341/70804816-a7fcdd00-1d74-11ea-8244-06ede764fa89.png">

<img width="1506" alt="Screen Shot 2019-12-13 at 6 47 55 AM" src="https://user-images.githubusercontent.com/3457341/70804822-ad5a2780-1d74-11ea-81e7-300dd9a7f896.png">

<img width="1506" alt="Screen Shot 2019-12-13 at 6 48 04 AM" src="https://user-images.githubusercontent.com/3457341/70804828-b0edae80-1d74-11ea-9001-a9b501e86623.png">

## TODO

- [x] Threshold inputs on character wound and strain are too small.
- [x] Get range and skill in character attacks aligned properly (Firefox).
- [x] Critical in vehicle weapons is misaligned (Chrome) and critical and range (Firefox).
- [x] Vehicle attachment name alignment.

**Comment by sparkertime** [comment]
Two separate comments:

First, wow that looks great! Consider me interested!

More generally, I love love LOVE that you are engaging so much. Crazy week for me professionally so I haven't had time to start reviewing your PRs, but expect some comments over the weekend. I want to make sure virtually all of these make their way into production, and I just want to make sure you don't interpret my silence as disinterest!

To be continued!

**Comment by duffn** [comment]
No problem, I know how that goes!

I'm happy to be contributing and look forward to your comments!
